name: Hugo to Pages and Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build with Hugo
        run: hugo --minify

      # ESTE PASO SUBE LA CARPETA PUBLIC A GITHUB PAGES AUTOMÁTICAMENTE
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public

      # ESTE PASO ENVÍA LO MISMO A AZURE
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_423724681E114DA8996A4BC271A63430 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_FDDF3B3DCFC040F0A1E5100A79869EAE }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_468DBE163D614E44B1A822501FDA3212 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'hmis-JenkinsAbuser'
          package: ./public
