# Hugo deployment to Azure Web App - hmis-JenkinsAbuser
name: Build and deploy Hugo site to Azure Web App - hmis-JenkinsAbuser

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive  # Carga el tema hugo-blog-awesome si es un submodulo
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true # Necesario para muchos temas modernos

      - name: Build with Hugo
        run: hugo --minify

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: hugo-site
          path: public/  # Solo subimos la carpeta con los HTML generados

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write 
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: hugo-site
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_423724681E114DA8996A4BC271A63430 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_FDDF3B3DCFC040F0A1E5100A79869EAE }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_468DBE163D614E44B1A822501FDA3212 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'hmis-JenkinsAbuser'
          slot-name: 'Production'
          package: . # Despliega el contenido del artefacto descargado
